package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.BusinessRole;

public interface BusinessRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(BusinessRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(BusinessRole record);
}