package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.BusinessData;
import org.apache.ibatis.annotations.Mapper;

@Mapper()
public interface BusinessDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_data
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(BusinessData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_data
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(BusinessData record);
}