package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.BusinessRole;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(BusinessRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(BusinessRole record);

    List<Long> selectBusinessId(@Param("roleIds") List<Long> roleIds);


}