package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Business;
import cn.edu.buaa.rec.model.BusinessWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(BusinessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(BusinessWithBLOBs record);

    Business selectBusiness(Long businessId);

    List<Business> selectBusinessByIds(@Param("ids")List<Long> ids);
}