package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.QuestionScenario;

public interface QuestionScenarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(QuestionScenario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(QuestionScenario record);
}