package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Solution;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SolutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(Solution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(Solution record);

    List<Solution> selectByProjectId(Long id);

    List<Solution> selectByProjectIdAndUserId(@Param("projectId")Long projectId,@Param("userId") Long userId);

    Long selectMaxId();

    int checkByTitleAndProjectId(@Param("title")String title,@Param("projectId")Long projectid);
}