package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UsecaseRole;

public interface UsecaseRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(UsecaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_role
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(UsecaseRole record);
}