package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserProject;

import java.util.List;

public interface UserProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated Mon Mar 05 21:11:02 CST 2018
     */
    int insert(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project
     *
     * @mbggenerated Mon Mar 05 21:11:02 CST 2018
     */
    int insertSelective(UserProject record);

    List<Long> selectByUserId(Long userId);
}