package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserProjectMan;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserProjectManMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_man
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(UserProjectMan record);

    List<Long> selectProjectByUserId(@Param("userId") Long userId);

    List<Long> selectUserByProjectId(@Param("projectIds") List<Long> projectIds);

    List<Long> selectProjectByUserIdWithNoApproved(@Param("userId") Long userId);

    int updateApproved(@Param("id") Long id);

    List<Long> selectManProjectId(Long userId);

    List<UserProjectMan> selectManApply(@Param("manProjectIds") List<Long> manProjectIds);
}