package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserDomain;

public interface UserDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(UserDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_domain
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(UserDomain record);
}