package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ActivityRole;
import cn.edu.buaa.rec.model.ActivityRoleExample;

public interface ActivityRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_role
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int countByExample(ActivityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_role
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(ActivityRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_role
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(ActivityRole record);
}