package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Activity;
import cn.edu.buaa.rec.model.ActivityWithBLOBs;
import java.util.List;

public interface ActivityMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insert(ActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insertSelective(ActivityWithBLOBs record);

    List<Activity> selectByScenarioId(Long scenarioId);

}