package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ActivityData;

public interface ActivityDataMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(ActivityData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_data
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(ActivityData record);
}