package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Activity;
import cn.edu.buaa.rec.model.ActivityExample;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(Activity record);
}