package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Data;
import cn.edu.buaa.rec.model.DataExample;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(Data record);
}