package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Detection;
import cn.edu.buaa.rec.model.DetectionExample;

public interface DetectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(DetectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(Detection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(Detection record);
}