package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.DomainProject;
import cn.edu.buaa.rec.model.DomainProjectExample;

public interface DomainProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_project
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(DomainProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_project
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(DomainProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_project
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(DomainProject record);
}