package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Domain;

public interface DomainMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insert(Domain record);

    Long selectMaxId();

    Domain selectByName(String name);

    Domain selectById(Long id);
}