package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Domain;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insertSelective(Domain record);

    Domain selectByName(String name);

    Long selectMaxId();

    Domain selectById(Long id);
}