package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Project;

import java.util.List;

public interface ProjectMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(Project record);

    Long selectMaxId();

    Project selectByName(String name);

    List<Project> selectAll();

    Project selectById(Long projectId);
}