package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Project;
import java.util.List;

public interface ProjectMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insertSelective(Project record);

    Long selectMaxId();

    Project selectByName(String name);

    Project selectById(Long id);

    List<Project> selectAll();
}