package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.QuestionScenario;
import cn.edu.buaa.rec.model.QuestionScenarioExample;

public interface QuestionScenarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(QuestionScenarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(QuestionScenario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(QuestionScenario record);
}