package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.QuestionBusiness;
import cn.edu.buaa.rec.model.QuestionBusinessExample;

public interface QuestionBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_business
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(QuestionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_business
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(QuestionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_business
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(QuestionBusiness record);
}