package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Question;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    int insertSelective(Question record);
}