package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Review;
import cn.edu.buaa.rec.model.ReviewExample;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(ReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(Review record);
}