package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Review;

public interface ReviewMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */

}