package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Role;

import java.util.List;


public interface RoleMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insertSelective(Role record);

    Role selectById(Long id);

    List<Role> selectByProjectId(Long id);
}