package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.RoleActivity;

public interface RoleActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_activity
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(RoleActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_activity
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(RoleActivity record);
}