package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.RoleActivity;
import cn.edu.buaa.rec.model.RoleActivityExample;

public interface RoleActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_activity
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(RoleActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_activity
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(RoleActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_activity
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(RoleActivity record);
}