package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioData;
import cn.edu.buaa.rec.model.ScenarioDataExample;

import java.util.List;

public interface ScenarioDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_data
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int countByExample(ScenarioDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_data
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(ScenarioData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_data
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(ScenarioData record);

    List<ScenarioData> selectByScenarioId(Long scenarioId);
}