package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioRole;

import java.util.List;

public interface ScenarioRoleMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_role
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    int insert(ScenarioRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_role
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    int insertSelective(ScenarioRole record);

    List<ScenarioRole> selectByScenarioId(Long scenarioId);
}