package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Scenario;

public interface ScenarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(Scenario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(Scenario record);
}