package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioRole;
import cn.edu.buaa.rec.model.ScenarioRoleExample;

import java.util.List;

public interface ScenarioRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_role
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int countByExample(ScenarioRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_role
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insert(ScenarioRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_role
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insertSelective(ScenarioRole record);

    List<ScenarioRole> selectByScenarioId(Long scenarioId);
}