package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioBusiness;
import cn.edu.buaa.rec.model.ScenarioBusinessExample;

public interface ScenarioBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_business
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int countByExample(ScenarioBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_business
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insert(ScenarioBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_business
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    int insertSelective(ScenarioBusiness record);
}