package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Scenario;
import cn.edu.buaa.rec.model.ScenarioExample;

import java.util.List;

public interface ScenarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int countByExample(ScenarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(Scenario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(Scenario record);

    List<Scenario> selectByProjectId(Long projectId);

    Scenario selectByName(String name);
}