package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioBusiness;

public interface ScenarioBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(ScenarioBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_business
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(ScenarioBusiness record);
}