package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioUsecase;

public interface ScenarioUsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_usecase
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(ScenarioUsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_usecase
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(ScenarioUsecase record);
}