package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.ScenarioData;
import com.sun.tools.javac.util.List;

public interface ScenarioDataMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_data
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    int insert(ScenarioData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenario_data
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    int insertSelective(ScenarioData record);

    List<ScenarioData> selectByScenarioId(Long scenarioId);
}