package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Solution;
import cn.edu.buaa.rec.model.SolutionExample;

import java.util.List;

public interface SolutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int countByExample(SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insert(Solution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insertSelective(Solution record);

    List<Solution> selectByProjectId(Long id);
}