package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestionScenario;

public interface SolutionQuestionScenarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(SolutionQuestionScenario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_scenario
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(SolutionQuestionScenario record);
}