package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestion;
import cn.edu.buaa.rec.model.SolutionQuestionExample;

public interface SolutionQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(SolutionQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(SolutionQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(SolutionQuestion record);
}