package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestionBusiness;
import cn.edu.buaa.rec.model.SolutionQuestionBusinessExample;

public interface SolutionQuestionBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_business
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(SolutionQuestionBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_business
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(SolutionQuestionBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_business
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(SolutionQuestionBusiness record);
}