package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestionScenario;
import cn.edu.buaa.rec.model.SolutionQuestionScenarioExample;

public interface SolutionQuestionScenarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(SolutionQuestionScenarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(SolutionQuestionScenario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(SolutionQuestionScenario record);
}