package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestionUsecase;

public interface SolutionQuestionUsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_usecase
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insert(SolutionQuestionUsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_usecase
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    int insertSelective(SolutionQuestionUsecase record);
}