package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SolutionQuestionUsecase;
import cn.edu.buaa.rec.model.SolutionQuestionUsecaseExample;

public interface SolutionQuestionUsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_usecase
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(SolutionQuestionUsecaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_usecase
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(SolutionQuestionUsecase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solution_question_usecase
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(SolutionQuestionUsecase record);
}