package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.SysUser;

public interface SysUserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Feb 01 06:11:03 CST 2018
     */
    int insert(SysUser record);

    Long selectMaxId();

    SysUser selectByName(String name);

    int updateByName(SysUser sysUserInfo);

    SysUser selectById(Long id);
}