package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.Usecase;
import cn.edu.buaa.rec.model.UsecaseWithBLOBs;

import java.util.List;

public interface UsecaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insert(UsecaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    int insertSelective(UsecaseWithBLOBs record);

    List<Usecase> selectByProjectId(Long projectId);

    Usecase selectById(Long id);

    Usecase selectByName(String name);
}