package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UsecaseActivity;
import cn.edu.buaa.rec.model.UsecaseActivityExample;

public interface UsecaseActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_activity
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int countByExample(UsecaseActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_activity
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insert(UsecaseActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_activity
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insertSelective(UsecaseActivity record);
}