package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UsecaseBusiness;
import cn.edu.buaa.rec.model.UsecaseBusinessExample;

public interface UsecaseBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_business
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(UsecaseBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_business
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(UsecaseBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase_business
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(UsecaseBusiness record);
}