package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UsecaseExample;
import cn.edu.buaa.rec.model.UsecaseWithBLOBs;

public interface UsecaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(UsecaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(UsecaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usecase
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(UsecaseWithBLOBs record);
}