package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserProjectRole;
import cn.edu.buaa.rec.model.UserProjectRoleExample;

import java.util.List;

public interface UserProjectRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_role
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int countByExample(UserProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_role
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insert(UserProjectRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_role
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    int insertSelective(UserProjectRole record);

    List<UserProjectRole> selectBySysUserId(Long sysUserId);
}