package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserProjectRole;
import cn.edu.buaa.rec.model.UserProjectRoleExample;

public interface UserProjectRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_role
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int countByExample(UserProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_role
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(UserProjectRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_role
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(UserProjectRole record);
}