package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserExample;
import cn.edu.buaa.rec.model.UserWithBLOBs;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insert(UserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    int insertSelective(UserWithBLOBs record);
}