package cn.edu.buaa.rec.dao;

import cn.edu.buaa.rec.model.UserProjectMan;
import cn.edu.buaa.rec.model.UserProjectManExample;

public interface UserProjectManMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_man
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int countByExample(UserProjectManExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_man
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insert(UserProjectMan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_project_man
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    int insertSelective(UserProjectMan record);
}