package cn.edu.buaa.rec.model;

public class ScenarioUsecase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_usecase.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_usecase.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long scenarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_usecase.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long usecaseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_usecase.id
     *
     * @return the value of scenario_usecase.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_usecase.id
     *
     * @param id the value for scenario_usecase.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_usecase.scenario_id
     *
     * @return the value of scenario_usecase.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_usecase.scenario_id
     *
     * @param scenarioId the value for scenario_usecase.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_usecase.usecase_id
     *
     * @return the value of scenario_usecase.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_usecase.usecase_id
     *
     * @param usecaseId the value for scenario_usecase.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }
}