package cn.edu.buaa.rec.model;

public class ActivityData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.data_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.id
     *
     * @return the value of activity_data.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.id
     *
     * @param id the value for activity_data.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.activity_id
     *
     * @return the value of activity_data.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.activity_id
     *
     * @param activityId the value for activity_data.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.data_id
     *
     * @return the value of activity_data.data_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.data_id
     *
     * @param dataId the value for activity_data.data_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }
}