package cn.edu.buaa.rec.model;

public class ActivityWithBLOBs extends Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.description
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.pre_condition
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private String preCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.post_condition
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private String postCondition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.description
     *
     * @return the value of activity.description
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.description
     *
     * @param description the value for activity.description
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.pre_condition
     *
     * @return the value of activity.pre_condition
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public String getPreCondition() {
        return preCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.pre_condition
     *
     * @param preCondition the value for activity.pre_condition
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setPreCondition(String preCondition) {
        this.preCondition = preCondition == null ? null : preCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.post_condition
     *
     * @return the value of activity.post_condition
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public String getPostCondition() {
        return postCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.post_condition
     *
     * @param postCondition the value for activity.post_condition
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setPostCondition(String postCondition) {
        this.postCondition = postCondition == null ? null : postCondition.trim();
    }
}