package cn.edu.buaa.rec.model;

public class ActivityRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_role.activity_role_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    private Integer activityRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_role.activity_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_role.role_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_role.activity_role_id
     *
     * @return the value of activity_role.activity_role_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public Integer getActivityRoleId() {
        return activityRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_role.activity_role_id
     *
     * @param activityRoleId the value for activity_role.activity_role_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public void setActivityRoleId(Integer activityRoleId) {
        this.activityRoleId = activityRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_role.activity_id
     *
     * @return the value of activity_role.activity_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_role.activity_id
     *
     * @param activityId the value for activity_role.activity_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_role.role_id
     *
     * @return the value of activity_role.role_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_role.role_id
     *
     * @param roleId the value for activity_role.role_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}