package cn.edu.buaa.rec.model;

public class ActivityRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_role.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_role.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_role.role_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_role.id
     *
     * @return the value of activity_role.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_role.id
     *
     * @param id the value for activity_role.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_role.activity_id
     *
     * @return the value of activity_role.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_role.activity_id
     *
     * @param activityId the value for activity_role.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_role.role_id
     *
     * @return the value of activity_role.role_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_role.role_id
     *
     * @param roleId the value for activity_role.role_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}