package cn.edu.buaa.rec.model;

public class ActivityData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.activity_data_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    private Integer activityDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.activity_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_data.data_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    private Long dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.activity_data_id
     *
     * @return the value of activity_data.activity_data_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public Integer getActivityDataId() {
        return activityDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.activity_data_id
     *
     * @param activityDataId the value for activity_data.activity_data_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public void setActivityDataId(Integer activityDataId) {
        this.activityDataId = activityDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.activity_id
     *
     * @return the value of activity_data.activity_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.activity_id
     *
     * @param activityId the value for activity_data.activity_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_data.data_id
     *
     * @return the value of activity_data.data_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_data.data_id
     *
     * @param dataId the value for activity_data.data_id
     *
     * @mbggenerated Tue Feb 06 02:42:05 CST 2018
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }
}