package cn.edu.buaa.rec.model;

public class BusinessWithBLOBs extends Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.description
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.flow
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String flow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.description
     *
     * @return the value of business.description
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.description
     *
     * @param description the value for business.description
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.flow
     *
     * @return the value of business.flow
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.flow
     *
     * @param flow the value for business.flow
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setFlow(String flow) {
        this.flow = flow == null ? null : flow.trim();
    }
}