package cn.edu.buaa.rec.model;

import java.util.Date;

public class Detection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long scenarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.result
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.id
     *
     * @return the value of detection.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.id
     *
     * @param id the value for detection.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.type
     *
     * @return the value of detection.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.type
     *
     * @param type the value for detection.type
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.scenario_id
     *
     * @return the value of detection.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.scenario_id
     *
     * @param scenarioId the value for detection.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.business_id
     *
     * @return the value of detection.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.business_id
     *
     * @param businessId the value for detection.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.usecase_id
     *
     * @return the value of detection.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.usecase_id
     *
     * @param usecaseId the value for detection.usecase_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.time
     *
     * @return the value of detection.time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.time
     *
     * @param time the value for detection.time
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.result
     *
     * @return the value of detection.result
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.result
     *
     * @param result the value for detection.result
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}