package cn.edu.buaa.rec.model;

public class DomainProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_project.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_project.project_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_project.domain_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long domainId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_project.id
     *
     * @return the value of domain_project.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_project.id
     *
     * @param id the value for domain_project.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_project.project_id
     *
     * @return the value of domain_project.project_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_project.project_id
     *
     * @param projectId the value for domain_project.project_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_project.domain_id
     *
     * @return the value of domain_project.domain_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_project.domain_id
     *
     * @param domainId the value for domain_project.domain_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }
}