package cn.edu.buaa.rec.model;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.domain_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.use_state
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String useState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.step
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Integer step;

    public Project(String name, String description, Long domainId, Long creatorId) {
        this.name = name;
        this.description = description;
        this.domainId = domainId;
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.description
     *
     * @return the value of project.description
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.description
     *
     * @param description the value for project.description
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.build_time
     *
     * @return the value of project.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.build_time
     *
     * @param buildTime the value for project.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.creator_id
     *
     * @return the value of project.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.creator_id
     *
     * @param creatorId the value for project.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.domain_id
     *
     * @return the value of project.domain_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.domain_id
     *
     * @param domainId the value for project.domain_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.use_state
     *
     * @return the value of project.use_state
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getUseState() {
        return useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.use_state
     *
     * @param useState the value for project.use_state
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setUseState(String useState) {
        this.useState = useState == null ? null : useState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.step
     *
     * @return the value of project.step
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.step
     *
     * @param step the value for project.step
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}