package cn.edu.buaa.rec.model;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.project_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.creator_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_title
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private String questionTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.build_time
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.update_time
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_description
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    private String questionDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_id
     *
     * @return the value of question.question_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_id
     *
     * @param questionId the value for question.question_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.project_id
     *
     * @return the value of question.project_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.project_id
     *
     * @param projectId the value for question.project_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.creator_id
     *
     * @return the value of question.creator_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.creator_id
     *
     * @param creatorId the value for question.creator_id
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_title
     *
     * @return the value of question.question_title
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public String getQuestionTitle() {
        return questionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_title
     *
     * @param questionTitle the value for question.question_title
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle == null ? null : questionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.build_time
     *
     * @return the value of question.build_time
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.build_time
     *
     * @param buildTime the value for question.build_time
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.update_time
     *
     * @return the value of question.update_time
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.update_time
     *
     * @param updateTime the value for question.update_time
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type
     *
     * @return the value of question.type
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type
     *
     * @param type the value for question.type
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_description
     *
     * @return the value of question.question_description
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public String getQuestionDescription() {
        return questionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_description
     *
     * @param questionDescription the value for question.question_description
     *
     * @mbggenerated Thu Jan 25 01:16:54 CST 2018
     */
    public void setQuestionDescription(String questionDescription) {
        this.questionDescription = questionDescription == null ? null : questionDescription.trim();
    }
}