package cn.edu.buaa.rec.model;

public class QuestionScenario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_scenario.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_scenario.question_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_scenario.scenario_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long scenarioId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_scenario.id
     *
     * @return the value of question_scenario.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_scenario.id
     *
     * @param id the value for question_scenario.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_scenario.question_id
     *
     * @return the value of question_scenario.question_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_scenario.question_id
     *
     * @param questionId the value for question_scenario.question_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_scenario.scenario_id
     *
     * @return the value of question_scenario.scenario_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_scenario.scenario_id
     *
     * @param scenarioId the value for question_scenario.scenario_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }
}