package cn.edu.buaa.rec.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReviewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public ReviewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioIsNull() {
            addCriterion("type_scenario is null");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioIsNotNull() {
            addCriterion("type_scenario is not null");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioEqualTo(Integer value) {
            addCriterion("type_scenario =", value, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioNotEqualTo(Integer value) {
            addCriterion("type_scenario <>", value, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioGreaterThan(Integer value) {
            addCriterion("type_scenario >", value, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioGreaterThanOrEqualTo(Integer value) {
            addCriterion("type_scenario >=", value, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioLessThan(Integer value) {
            addCriterion("type_scenario <", value, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioLessThanOrEqualTo(Integer value) {
            addCriterion("type_scenario <=", value, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioIn(List<Integer> values) {
            addCriterion("type_scenario in", values, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioNotIn(List<Integer> values) {
            addCriterion("type_scenario not in", values, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioBetween(Integer value1, Integer value2) {
            addCriterion("type_scenario between", value1, value2, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andTypeScenarioNotBetween(Integer value1, Integer value2) {
            addCriterion("type_scenario not between", value1, value2, "typeScenario");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNull() {
            addCriterion("business_id is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIsNotNull() {
            addCriterion("business_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessIdEqualTo(Long value) {
            addCriterion("business_id =", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotEqualTo(Long value) {
            addCriterion("business_id <>", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThan(Long value) {
            addCriterion("business_id >", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdGreaterThanOrEqualTo(Long value) {
            addCriterion("business_id >=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThan(Long value) {
            addCriterion("business_id <", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdLessThanOrEqualTo(Long value) {
            addCriterion("business_id <=", value, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdIn(List<Long> values) {
            addCriterion("business_id in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotIn(List<Long> values) {
            addCriterion("business_id not in", values, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdBetween(Long value1, Long value2) {
            addCriterion("business_id between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andBusinessIdNotBetween(Long value1, Long value2) {
            addCriterion("business_id not between", value1, value2, "businessId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdIsNull() {
            addCriterion("usecase_id is null");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdIsNotNull() {
            addCriterion("usecase_id is not null");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdEqualTo(Long value) {
            addCriterion("usecase_id =", value, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdNotEqualTo(Long value) {
            addCriterion("usecase_id <>", value, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdGreaterThan(Long value) {
            addCriterion("usecase_id >", value, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("usecase_id >=", value, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdLessThan(Long value) {
            addCriterion("usecase_id <", value, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdLessThanOrEqualTo(Long value) {
            addCriterion("usecase_id <=", value, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdIn(List<Long> values) {
            addCriterion("usecase_id in", values, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdNotIn(List<Long> values) {
            addCriterion("usecase_id not in", values, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdBetween(Long value1, Long value2) {
            addCriterion("usecase_id between", value1, value2, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andUsecaseIdNotBetween(Long value1, Long value2) {
            addCriterion("usecase_id not between", value1, value2, "usecaseId");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNull() {
            addCriterion("topic_id is null");
            return (Criteria) this;
        }

        public Criteria andTopicIdIsNotNull() {
            addCriterion("topic_id is not null");
            return (Criteria) this;
        }

        public Criteria andTopicIdEqualTo(Long value) {
            addCriterion("topic_id =", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotEqualTo(Long value) {
            addCriterion("topic_id <>", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThan(Long value) {
            addCriterion("topic_id >", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdGreaterThanOrEqualTo(Long value) {
            addCriterion("topic_id >=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThan(Long value) {
            addCriterion("topic_id <", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdLessThanOrEqualTo(Long value) {
            addCriterion("topic_id <=", value, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdIn(List<Long> values) {
            addCriterion("topic_id in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotIn(List<Long> values) {
            addCriterion("topic_id not in", values, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdBetween(Long value1, Long value2) {
            addCriterion("topic_id between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andTopicIdNotBetween(Long value1, Long value2) {
            addCriterion("topic_id not between", value1, value2, "topicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdIsNull() {
            addCriterion("sub_topic_id is null");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdIsNotNull() {
            addCriterion("sub_topic_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdEqualTo(Long value) {
            addCriterion("sub_topic_id =", value, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdNotEqualTo(Long value) {
            addCriterion("sub_topic_id <>", value, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdGreaterThan(Long value) {
            addCriterion("sub_topic_id >", value, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sub_topic_id >=", value, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdLessThan(Long value) {
            addCriterion("sub_topic_id <", value, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdLessThanOrEqualTo(Long value) {
            addCriterion("sub_topic_id <=", value, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdIn(List<Long> values) {
            addCriterion("sub_topic_id in", values, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdNotIn(List<Long> values) {
            addCriterion("sub_topic_id not in", values, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdBetween(Long value1, Long value2) {
            addCriterion("sub_topic_id between", value1, value2, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andSubTopicIdNotBetween(Long value1, Long value2) {
            addCriterion("sub_topic_id not between", value1, value2, "subTopicId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("creator_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(Long value) {
            addCriterion("creator_id =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(Long value) {
            addCriterion("creator_id <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(Long value) {
            addCriterion("creator_id >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("creator_id >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(Long value) {
            addCriterion("creator_id <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(Long value) {
            addCriterion("creator_id <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<Long> values) {
            addCriterion("creator_id in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<Long> values) {
            addCriterion("creator_id not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(Long value1, Long value2) {
            addCriterion("creator_id between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(Long value1, Long value2) {
            addCriterion("creator_id not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andResponseIdIsNull() {
            addCriterion("response_id is null");
            return (Criteria) this;
        }

        public Criteria andResponseIdIsNotNull() {
            addCriterion("response_id is not null");
            return (Criteria) this;
        }

        public Criteria andResponseIdEqualTo(Long value) {
            addCriterion("response_id =", value, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdNotEqualTo(Long value) {
            addCriterion("response_id <>", value, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdGreaterThan(Long value) {
            addCriterion("response_id >", value, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("response_id >=", value, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdLessThan(Long value) {
            addCriterion("response_id <", value, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdLessThanOrEqualTo(Long value) {
            addCriterion("response_id <=", value, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdIn(List<Long> values) {
            addCriterion("response_id in", values, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdNotIn(List<Long> values) {
            addCriterion("response_id not in", values, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdBetween(Long value1, Long value2) {
            addCriterion("response_id between", value1, value2, "responseId");
            return (Criteria) this;
        }

        public Criteria andResponseIdNotBetween(Long value1, Long value2) {
            addCriterion("response_id not between", value1, value2, "responseId");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 27 16:57:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}