package cn.edu.buaa.rec.model;

import java.util.Date;

public class Review {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.type_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Integer typeScenario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.business_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.usecase_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.topic_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.sub_topic_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long subTopicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.type
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.creator_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.response_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Long responseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.time
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.content
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.type_scenario
     *
     * @return the value of review.type_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Integer getTypeScenario() {
        return typeScenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.type_scenario
     *
     * @param typeScenario the value for review.type_scenario
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setTypeScenario(Integer typeScenario) {
        this.typeScenario = typeScenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.business_id
     *
     * @return the value of review.business_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.business_id
     *
     * @param businessId the value for review.business_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.usecase_id
     *
     * @return the value of review.usecase_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.usecase_id
     *
     * @param usecaseId the value for review.usecase_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.topic_id
     *
     * @return the value of review.topic_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.topic_id
     *
     * @param topicId the value for review.topic_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.sub_topic_id
     *
     * @return the value of review.sub_topic_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getSubTopicId() {
        return subTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.sub_topic_id
     *
     * @param subTopicId the value for review.sub_topic_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setSubTopicId(Long subTopicId) {
        this.subTopicId = subTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.type
     *
     * @return the value of review.type
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.type
     *
     * @param type the value for review.type
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.creator_id
     *
     * @return the value of review.creator_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.creator_id
     *
     * @param creatorId the value for review.creator_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.response_id
     *
     * @return the value of review.response_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Long getResponseId() {
        return responseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.response_id
     *
     * @param responseId the value for review.response_id
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setResponseId(Long responseId) {
        this.responseId = responseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.time
     *
     * @return the value of review.time
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.time
     *
     * @param time the value for review.time
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.content
     *
     * @return the value of review.content
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.content
     *
     * @param content the value for review.content
     *
     * @mbggenerated Tue Feb 27 16:57:54 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}