package cn.edu.buaa.rec.model;

public class ScenarioData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_data.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_data.scenario_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long scenarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_data.data_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_data.id
     *
     * @return the value of scenario_data.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_data.id
     *
     * @param id the value for scenario_data.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_data.scenario_id
     *
     * @return the value of scenario_data.scenario_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_data.scenario_id
     *
     * @param scenarioId the value for scenario_data.scenario_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_data.data_id
     *
     * @return the value of scenario_data.data_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_data.data_id
     *
     * @param dataId the value for scenario_data.data_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }
}