package cn.edu.buaa.rec.model;

public class ScenarioData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_data.scenario_data_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long scenarioDataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_data.scenario_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long scenarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_data.data_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long dataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_data.scenario_data_id
     *
     * @return the value of scenario_data.scenario_data_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getScenarioDataId() {
        return scenarioDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_data.scenario_data_id
     *
     * @param scenarioDataId the value for scenario_data.scenario_data_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setScenarioDataId(Long scenarioDataId) {
        this.scenarioDataId = scenarioDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_data.scenario_id
     *
     * @return the value of scenario_data.scenario_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_data.scenario_id
     *
     * @param scenarioId the value for scenario_data.scenario_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_data.data_id
     *
     * @return the value of scenario_data.data_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_data.data_id
     *
     * @param dataId the value for scenario_data.data_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setDataId(Long dataId) {
        this.dataId = dataId;
    }
}