package cn.edu.buaa.rec.model;

import java.util.Date;

public class Scenario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.name
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.project_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.creator_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.build_time
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.update_time
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario.use_state
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Integer useState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.id
     *
     * @return the value of scenario.id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.id
     *
     * @param id the value for scenario.id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.name
     *
     * @return the value of scenario.name
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.name
     *
     * @param name the value for scenario.name
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.project_id
     *
     * @return the value of scenario.project_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.project_id
     *
     * @param projectId the value for scenario.project_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.creator_id
     *
     * @return the value of scenario.creator_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.creator_id
     *
     * @param creatorId the value for scenario.creator_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.build_time
     *
     * @return the value of scenario.build_time
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.build_time
     *
     * @param buildTime the value for scenario.build_time
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.update_time
     *
     * @return the value of scenario.update_time
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.update_time
     *
     * @param updateTime the value for scenario.update_time
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario.use_state
     *
     * @return the value of scenario.use_state
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Integer getUseState() {
        return useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario.use_state
     *
     * @param useState the value for scenario.use_state
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setUseState(Integer useState) {
        this.useState = useState;
    }
}