package cn.edu.buaa.rec.model;

public class ScenarioRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_role.scenario_role_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long scenarioRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_role.scenario_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long scenarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_role.role_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_role.scenario_role_id
     *
     * @return the value of scenario_role.scenario_role_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getScenarioRoleId() {
        return scenarioRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_role.scenario_role_id
     *
     * @param scenarioRoleId the value for scenario_role.scenario_role_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setScenarioRoleId(Long scenarioRoleId) {
        this.scenarioRoleId = scenarioRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_role.scenario_id
     *
     * @return the value of scenario_role.scenario_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_role.scenario_id
     *
     * @param scenarioId the value for scenario_role.scenario_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_role.role_id
     *
     * @return the value of scenario_role.role_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_role.role_id
     *
     * @param roleId the value for scenario_role.role_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}