package cn.edu.buaa.rec.model;

public class ScenarioBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_business.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long scenarioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenario_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_business.id
     *
     * @return the value of scenario_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_business.id
     *
     * @param id the value for scenario_business.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_business.scenario_id
     *
     * @return the value of scenario_business.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_business.scenario_id
     *
     * @param scenarioId the value for scenario_business.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenario_business.business_id
     *
     * @return the value of scenario_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenario_business.business_id
     *
     * @param businessId the value for scenario_business.business_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }
}