package cn.edu.buaa.rec.model;

public class SolutionQuestionBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_business.id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_business.solution_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long solutionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_business.question_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_business.business_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long businessId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_business.id
     *
     * @return the value of solution_question_business.id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_business.id
     *
     * @param id the value for solution_question_business.id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_business.solution_id
     *
     * @return the value of solution_question_business.solution_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_business.solution_id
     *
     * @param solutionId the value for solution_question_business.solution_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setSolutionId(Long solutionId) {
        this.solutionId = solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_business.question_id
     *
     * @return the value of solution_question_business.question_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_business.question_id
     *
     * @param questionId the value for solution_question_business.question_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_business.business_id
     *
     * @return the value of solution_question_business.business_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_business.business_id
     *
     * @param businessId the value for solution_question_business.business_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }
}