package cn.edu.buaa.rec.model;

import java.util.Date;

public class Solution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.name
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.project_id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.type
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution.description
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.id
     *
     * @return the value of solution.id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.id
     *
     * @param id the value for solution.id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.name
     *
     * @return the value of solution.name
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.name
     *
     * @param name the value for solution.name
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.build_time
     *
     * @return the value of solution.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.build_time
     *
     * @param buildTime the value for solution.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.update_time
     *
     * @return the value of solution.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.update_time
     *
     * @param updateTime the value for solution.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.project_id
     *
     * @return the value of solution.project_id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.project_id
     *
     * @param projectId the value for solution.project_id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.creator_id
     *
     * @return the value of solution.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.creator_id
     *
     * @param creatorId the value for solution.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.type
     *
     * @return the value of solution.type
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.type
     *
     * @param type the value for solution.type
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution.description
     *
     * @return the value of solution.description
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution.description
     *
     * @param description the value for solution.description
     *
     * @mbggenerated Mon Feb 05 20:59:37 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}