package cn.edu.buaa.rec.model;

public class SolutionQuestionScenario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_scenario.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_scenario.solution_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long solutionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_scenario.question_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solution_question_scenario.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    private Long scenarioId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_scenario.id
     *
     * @return the value of solution_question_scenario.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_scenario.id
     *
     * @param id the value for solution_question_scenario.id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_scenario.solution_id
     *
     * @return the value of solution_question_scenario.solution_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getSolutionId() {
        return solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_scenario.solution_id
     *
     * @param solutionId the value for solution_question_scenario.solution_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setSolutionId(Long solutionId) {
        this.solutionId = solutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_scenario.question_id
     *
     * @return the value of solution_question_scenario.question_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_scenario.question_id
     *
     * @param questionId the value for solution_question_scenario.question_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solution_question_scenario.scenario_id
     *
     * @return the value of solution_question_scenario.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public Long getScenarioId() {
        return scenarioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solution_question_scenario.scenario_id
     *
     * @param scenarioId the value for solution_question_scenario.scenario_id
     *
     * @mbggenerated Wed Feb 28 00:40:34 CST 2018
     */
    public void setScenarioId(Long scenarioId) {
        this.scenarioId = scenarioId;
    }
}