package cn.edu.buaa.rec.model;

public class UsecaseWithBLOBs extends Usecase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.description
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.rucm_spec
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private String rucmSpec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.description
     *
     * @return the value of usecase.description
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.description
     *
     * @param description the value for usecase.description
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.rucm_spec
     *
     * @return the value of usecase.rucm_spec
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public String getRucmSpec() {
        return rucmSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.rucm_spec
     *
     * @param rucmSpec the value for usecase.rucm_spec
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setRucmSpec(String rucmSpec) {
        this.rucmSpec = rucmSpec == null ? null : rucmSpec.trim();
    }
}