package cn.edu.buaa.rec.model;

public class UsecaseWithBLOBs extends Usecase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.des
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.pre_condition
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String preCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.post_condition
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String postCondition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.des
     *
     * @return the value of usecase.des
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.des
     *
     * @param des the value for usecase.des
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.pre_condition
     *
     * @return the value of usecase.pre_condition
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getPreCondition() {
        return preCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.pre_condition
     *
     * @param preCondition the value for usecase.pre_condition
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setPreCondition(String preCondition) {
        this.preCondition = preCondition == null ? null : preCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.post_condition
     *
     * @return the value of usecase.post_condition
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getPostCondition() {
        return postCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.post_condition
     *
     * @param postCondition the value for usecase.post_condition
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setPostCondition(String postCondition) {
        this.postCondition = postCondition == null ? null : postCondition.trim();
    }
}