package cn.edu.buaa.rec.model;

public class UsecaseActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_activity.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_activity.usecase_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_activity.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    private Long activityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_activity.id
     *
     * @return the value of usecase_activity.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_activity.id
     *
     * @param id the value for usecase_activity.id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_activity.usecase_id
     *
     * @return the value of usecase_activity.usecase_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_activity.usecase_id
     *
     * @param usecaseId the value for usecase_activity.usecase_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_activity.activity_id
     *
     * @return the value of usecase_activity.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_activity.activity_id
     *
     * @param activityId the value for usecase_activity.activity_id
     *
     * @mbggenerated Wed Feb 21 16:36:16 CST 2018
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
}