package cn.edu.buaa.rec.model;

public class UsecaseActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_activity.usecase_activity_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long usecaseActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_activity.usecase_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long usecaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase_activity.acticity_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    private Long acticityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_activity.usecase_activity_id
     *
     * @return the value of usecase_activity.usecase_activity_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getUsecaseActivityId() {
        return usecaseActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_activity.usecase_activity_id
     *
     * @param usecaseActivityId the value for usecase_activity.usecase_activity_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setUsecaseActivityId(Long usecaseActivityId) {
        this.usecaseActivityId = usecaseActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_activity.usecase_id
     *
     * @return the value of usecase_activity.usecase_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getUsecaseId() {
        return usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_activity.usecase_id
     *
     * @param usecaseId the value for usecase_activity.usecase_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setUsecaseId(Long usecaseId) {
        this.usecaseId = usecaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase_activity.acticity_id
     *
     * @return the value of usecase_activity.acticity_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public Long getActicityId() {
        return acticityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase_activity.acticity_id
     *
     * @param acticityId the value for usecase_activity.acticity_id
     *
     * @mbggenerated Sun Feb 18 09:09:16 CST 2018
     */
    public void setActicityId(Long acticityId) {
        this.acticityId = acticityId;
    }
}