package cn.edu.buaa.rec.model;

import java.util.Date;

public class Usecase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.name
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.priority
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.project_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usecase.role_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.id
     *
     * @return the value of usecase.id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.id
     *
     * @param id the value for usecase.id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.name
     *
     * @return the value of usecase.name
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.name
     *
     * @param name the value for usecase.name
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.priority
     *
     * @return the value of usecase.priority
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.priority
     *
     * @param priority the value for usecase.priority
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.build_time
     *
     * @return the value of usecase.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.build_time
     *
     * @param buildTime the value for usecase.build_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.update_time
     *
     * @return the value of usecase.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.update_time
     *
     * @param updateTime the value for usecase.update_time
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.project_id
     *
     * @return the value of usecase.project_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.project_id
     *
     * @param projectId the value for usecase.project_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.creator_id
     *
     * @return the value of usecase.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.creator_id
     *
     * @param creatorId the value for usecase.creator_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usecase.role_id
     *
     * @return the value of usecase.role_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usecase.role_id
     *
     * @param roleId the value for usecase.role_id
     *
     * @mbggenerated Mon Feb 05 20:59:36 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}