package cn.edu.buaa.rec.model;

public class UserDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_domain.id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_domain.user_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_domain.domain_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    private Long domainId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_domain.id
     *
     * @return the value of user_domain.id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_domain.id
     *
     * @param id the value for user_domain.id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_domain.user_id
     *
     * @return the value of user_domain.user_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_domain.user_id
     *
     * @param userId the value for user_domain.user_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_domain.domain_id
     *
     * @return the value of user_domain.domain_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public Long getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_domain.domain_id
     *
     * @param domainId the value for user_domain.domain_id
     *
     * @mbggenerated Tue Feb 27 16:57:55 CST 2018
     */
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }
}